### ISSUE TITLE
Manual install docs

### ISSUE THREAD

**Issue by OmgImAlexis** [hasura/docs#1]
I found your project on Youtube but can't find any instructions on how to install this via a manual install and I can't seem to find the source code for Hasura itself? Is it hosted somewhere else?

**Comment by 0x777** [comment]
Currently the docs are all over the place. Sorry about that. This repo is work in progress and will be in a much better state in a weeks time. We are in the middle of a major overhaul. 

Here are the instructions to install the platform locally (on your laptop) : https://github.com/hasura/local-development. To install hasura on your own infrastructure, you can sign up on https://beta.hasura.io. 

Regarding the source code, we haven't open sourced it yet. It is on the roadmap.

**Comment by dsandip** [comment]
@OmgImAlexis : We have included all the instructions on installing Hasura in one place [here](https://docs.hasura.io/0.13/ref/creating-a-project/index.html) (*the manual install instructions continue to redirect to the [github repo's README.md](https://github.com/hasura/local-development)*). Closing this issue, please reopen or raise another ticket with any suggestions you may have. Thanks!
