### ISSUE TITLE
Custom Microservices page has an error

### ISSUE THREAD

**Issue by achocolatebear** [hasura/docs#116]
In the opening sentence, the part that I have bolded is redundant. It should be removed: 

Custom microservices are services that are deployed by developers on Hasura using a git push command or by using one of the thousands of Docker images **or build and use their own images.**

**Comment by dsandip** [comment]
@achocolatebear : Thank you for pointing this out. While I don't agree that the sentence is redundant, it should be better formatted to get the point across like this:
*Custom microservices are services that are deployed by developers on Hasura using:*
1. `git push` command to automatically deploy code as a Docker image
1. 3rd party Docker image (e.g. [ghost](https://hub.docker.com/_/ghost/), [metabase](https://store.docker.com/community/images/metabase/metabase), etc.)
1. Custom Docker image

**Comment by dsandip** [comment]
The content for custom microservices has changed. No longer relevant.
