### ISSUE TITLE
Landing page design bug

### ISSUE THREAD

**Issue by dsandip** [hasura/docs#14]
**screenshot of design:**

![screen shot 2017-07-13 at 11 43 49 am](https://user-images.githubusercontent.com/24300818/28152962-aefec1ca-67c0-11e7-95f8-9524c97d4d3e.png)

**Screenshot of current implementation:**

![screen shot 2017-07-13 at 11 44 05 am](https://user-images.githubusercontent.com/24300818/28152993-cc3612e8-67c0-11e7-8b49-375818d9c3b3.png)

1. In the above image, there is a gap between the header and the bluish background for the cards, which does not conform to the 1st image/design. 
1. The gap between the header and the first row of cards and the space between two cards (*between the rows and column or between individual cards*) is the same in the design.

**Comment by surendran82** [comment]
Fixed the issue
