### ISSUE TITLE
Getting-started stubs for non-priority starter kits

### ISSUE THREAD

**Issue by dsandip** [hasura/docs#164]
Need content and links(on landing page) to the following getting-started guides:
- [x] csharp-aspnet
- [x] go-iris
- [x] go-raw
- [ ] haskell-spock
- [ ] java-play
- [x] java-spark
- [x] java-spring-boot
- [ ] js-angularjs
- [x] php-apache
- [ ] php-laravel
- [x] python-django
- [x] python-flask
- [ ] r-shiny
- [ ] ruby-rails  
- [x] swift-perfect
- [x] swift-vapor

**Comment by coco98** [comment]
@dsandip Can we close this issue and instead create a repository and issues to track work on creating more projects for hub?
I've already checked off those projects that are available now on hasura.io/hub.

**Comment by dsandip** [comment]
@coco98 : Created a private repo with an issue for each of the unchecked items in the list. https://github.com/hasura/hub-quickstarts/issues.
