### ISSUE TITLE
Manual->Deploying web app: modify content for new hasuractl instruction set

### ISSUE THREAD

**Issue by dsandip** [hasura/docs#168]
In the quickstarts and custom Dockerfile sections, update hasuractl commands and add new ones for adding routes, [SSH Keys](https://docs.hasura.io/0.14/manual/deploying-webapp/index.html#add-your-ssh-key) etc.

https://docs.hasura.io/0.14/manual/deploying-webapp/index.html#option-2-using-your-own-dockerfile-advanced-users

**Comment by dsandip** [comment]
@paranoidsp : I know you have updated the spreadsheet for part-1 but I just wanted to leave it in here to be sure.

**Comment by ecthiender** [comment]
fixed in 5696f13f08f7884136e4a0f54c42840992ecf0a5
