### ISSUE TITLE
Add algolia logo to docs search

### ISSUE THREAD

**Issue by coco98** [hasura/docs#175]
We have to add this, otherwise we can't use the free tier.

**Comment by dsandip** [comment]
@coco98: The logo is displayed along with the search results. Oh wait, are you referring to the tutorials/guides listing pages?

**Comment by coco98** [comment]
Algolia requires you to include their logo in the search bar for the free
tier.

**Comment by dsandip** [comment]
@coco98: Closing this one based on the email from algolia support.
