### ISSUE TITLE
Sphinx TOC design - change the font color

### ISSUE THREAD

**Issue by dsandip** [hasura/docs#18]
The existing link color is very hard to read in the TOC component in Sphinx. Please change it to the color here: https://projects.invisionapp.com/d/main#/console/11376491/243557830/preview

**Comment by karthikvt26** [comment]
Updated the color to rgba(207,156,14,1)

**Comment by dsandip** [comment]
Thanks @karthikvt26 . Here's the link for record anyway - https://projects.invisionapp.com/d/main#/console/11376491/243562036/inspect

**Comment by karthikvt26** [comment]
Closing this one for now
