### ISSUE TITLE
Living document: Established terminology/glossary

### ISSUE THREAD

**Issue by coco98** [hasura/docs#210]
_Last updated: Nov 3, 1.30pm_

**General**

- **cluster**: A bunch of nodes that are running a bunch of microservices
- **project**: all the source codez r here
- **microservice**: the word service should not be used. SEO value also.
- **node**: the word VM or server should not be used
- **app**: the frontend of an "application" (http://www.appcelerator.com/blog/2014/05/apps-v-applications/ ??)
- **~~backend~~**: This term should not be used anywhere. "server-side portion of your application". 
- **application**: The thing that is deployed on hasura. A Hasura project represents an application. A Hasura cluster is a running instance of an application
- **hub projects**: Projects that live on hasura.io/hub
- **starter projects**: hasura/hello-* or hasura/<lang>-<frame> projects on the hub

----------

**Data APIs**

- **Permissions**: We should remove access control, row-level permissions, authorisation etc unless we're trying to describe what permissions are

------------

**Auth APIs**

- **Authorization token**: Note the usage of 'z'. Session tokens should not be used except during an explanation or similar.

**Comment by ecthiender** [comment]
Looks good, except few discrepancies:

> microservice: the word service should not be used. SEO value also.

But hasura cli uses `hasura add service` in the command.

> Session token: Not authorisation tokens?

Auth API returns `auth_token` in the response

**Comment by coco98** [comment]
> But hasura cli uses hasura add service in the command.

Should we use the word "service" everywhere then? What about conflation with kubernetes services?

**Comment by coco98** [comment]
> Auth API returns auth_token in the response

What do you suggest finally then?

**Comment by ecthiender** [comment]
> Should we use the word "service" everywhere then? What about conflation with kubernetes services?

True. Not sure. Also typing `hasura microservice add` is bit of a stretch.

Can we call them authorization tokens everywhere? I can change auth APIs to return `session_token`, but that will changing docs/quickstarts/everything that uses the token.

**Comment by ecthiender** [comment]
I personally like session tokens. But the magnitude of the change, can we able?

**Comment by coco98** [comment]
**microservice** 
-  Pro: SEO, USP, value-prop points                    
-  Con: Is it technically correct? Adding a db/cron? Is everything a microservice?             

**service**                       
- Pro: shorter command to write   
- Con: Confustion with k8s service

--------
Common issues to both:

what if I'm adding some k8s configmaps or other objects that I want to deploy using git push hasura master? I create a folder for storing those k8s.yaml by doing `hasura service add` is it?

**Comment by coco98** [comment]
@ecthiender 
Yeah. I agree. Authorization token sounds much easier to deal with. Should we rename `auth_token` to `authorization_token` as well in that case?
Also, `Authorization: Bearer <token>` fits in better.

**Comment by ecthiender** [comment]
Renaming in auth API responses will require changing all docs/quickstarts/console/other code for new auth. What do you think about we use authorization tokens as a term everywhere, and let it be `auth_token` in the response? It still makes sense right? It is just abbreviated as `auth` in APIs.

**Comment by ecthiender** [comment]
>what if I'm adding some k8s configmaps or other objects that I want to deploy using git push hasura master? I create a folder for storing those k8s.yaml by doing hasura service add is it?

What will be the use-case where one wants to add k8s objects which are not part of any service/microservice?

**Comment by shahidhk** [comment]
> True. Not sure. Also typing hasura microservice add is bit of a stretch.

We can always alias things (like `po` for `pods`, `deploy` for `deployment`), we can have `ms` for `microservice`
`hasura ms add`

> backend: A running instance of a hasura project on a hasura cluster, viz. the backend of an "application". Typically a collection of microservices.

The `backend` terminology is quite confusing for me. 

I have an  app which has a frontend (html/css/js) and a backend (flask). Now when I host it on `hasura`, the `app` becomes a `microservice` (may be an nginx serving static files hosted on app.cluster.hasura-app.io). Now, what is the `backend`? Is the `cluster` the backend or my flask `microservice` (at api.cluster.hasura-app.io) the backend?

**Comment by shahidhk** [comment]
> what if I'm adding some k8s configmaps or other objects that I want to deploy using git push hasura master? I create a folder for storing those k8s.yaml by doing hasura service add is it?

This won't work right now, since `k8s.yaml` in services directory is supposed to have deployment and service objects. Also, like @ecthiender said, what could be the use case for such a situation?

**Comment by shahidhk** [comment]
> Session token: Not authorisation tokens?

I prefer `session_token` since it kind of tells me this thing can expire, it is for this session. `authorisation_token` has an associated meaning that it doesn't expire unless it is revoked

**Comment by coco98** [comment]
> What will be the use-case where one wants to add k8s objects which are not part of any service/microservice?

Adding a configmap, cronjob, daemonset, statefulset, namespace? Basically using kubernetes in a legitimate way. `hasura ms add` or `hasura svc add` doesn't make sense any more right?

> The backend terminology is quite confusing for me.

I completely agree. We should stop using the word backend and replace it with what? **Build X easily with Hasura**. What is **X** here?
@shahidhk @ecthiender This **X** is very important to figure out because it's the first word we use on our website.

Any ideas?

**Comment by coco98** [comment]
Should we rename **backend** to **application**?
@anandfeb25 @rajoshighosh This has an important implication for the website. **backend** doesn't capture webapp, which is a problem.

**Comment by shahidhk** [comment]
> Adding a configmap, cronjob, daemonset, statefulset, namespace? Basically using kubernetes in a legitimate way. `hasura ms add` or `hasura svc` add doesn't make sense any more right?

Correct. We need capture k8s objects that are not `hasura services/microservices`. 

One idea I can think of is to keep a `k8s` directory at the root of the project and to have a `yaml` file mandatorily for each service added to project. Everythong else in this directory is upto the user and it will all get applied on `git push`. Does that make sense @coco98 @0x777 ?

**Comment by coco98** [comment]
@shahidhk So we can safely ignore this for now. The question boils back down to `microservice` vs `service`.
Guys, thoughts?

**Comment by coco98** [comment]
Guys, as per discussion we are good to move to microservice to service.
Whatever you're working on, make sure you `grep, sed, and %s` your way to renaming service to microservice.

**Comment by ecthiender** [comment]
Auth sticks to authorization tokens (and `auth_token`s in the APIs).

**Comment by coco98** [comment]
Also, we're dropping the word 'backend' in favour of 'server-side portion of your application' as and when required.

**Comment by coco98** [comment]
@jaisontj @ecthiender @shahidhk @rikinsk 🖕🖕🖕🖕🖕🖕🖕🖕

**Comment by coco98** [comment]
Guys, another term to worry about.
`endpoints` or things that refer to the um..endpoint of an internal/external service.

The terms are:

1. `API`: https://data.anon18.hasura-app.io/v1/query/sdaf
2. `external endpoint`: `https://data.anon18.hasura-app.io`
3. `internal endpoint`: `http://data.anon18.hasura-app.io`

I'm not sure if the word `endpoint` makes sense.

@ecthiender @praveenweb @0x777 @jaisontj @paranoidsp pliss. show us the wayz.

**Comment by coco98** [comment]
Ok. Endpoint changes to URL.

**Comment by ecthiender** [comment]
cc: @0x777 let's call them URLs. External/Internal URLs.

**Comment by shahidhk** [comment]
Can we close this? @coco98 @rikinsk @0x777 @ecthiender ?

**Comment by shahidhk** [comment]
Closing this as terminologies are finalised. Re-open if required

**Comment by nnennajohn** [comment]
Hi. Can you please include in the docs on how to uninstall "temporarily" if you need. I've searched high and low and all through your docs and can't seem to find any reference to it? 

Thanks.
