### ISSUE TITLE
Remove google indexing for /ref/*

### ISSUE THREAD

**Issue by coco98** [hasura/docs#218]
Moved this here from #166
@karthikvt26 I've already removed them as build sources so 0.15/ref 0.15/tutorials 0.15/guides will all be 404s.

This is pushed to release-0.15. Once @dsandip verifies, you can make the release tomorrow.

**Comment by dsandip** [comment]
I've made a request to purge Google search cache.

**Comment by dsandip** [comment]
@coco98 : Can we also get rid of the release-0.6 branch?

**Comment by karthikvt26** [comment]
This is done. Please verify and close

https://docs.hasura.io/robots.txt
