### ISSUE TITLE
Instructions for what to do if a user does not have a starter project on /hub

### ISSUE THREAD

**Issue by coco98** [hasura/docs#219]
This requires thinking about the website also.

> I come to hasura.io and I find the "deploying cs section". Now, in the list of quickstarts given, my language is not there. Where are the instructions to add my own microservice ? (I know its there in the README but this should also be added on the homepage IMO)

**Comment by dsandip** [comment]
@coco98: Tracking it here: https://github.com/hasura/support/issues/479
