### ISSUE TITLE
Secrets? What are secrets? And other such existential questions.

### ISSUE THREAD

**Issue by coco98** [hasura/docs#223]

**Comment by paranoidsp** [comment]
This is not clear yet. There was a guy on Intercom today very frustrated with how the docs didn't mention that secrets had to be edited differently. He was trying to change notify conf, and shahidh had to take him step by step through the entire thing.

@ecthiender

**Comment by ecthiender** [comment]
We have this currently: https://docs.hasura.io/0.15/manual/project/secrets.html

Is this enough or needs more details? @paranoidsp @coco98 @shahidhk ?

**Comment by paranoidsp** [comment]
The page is good enough, but there are interns that aren't able to figure out that this is the page they need, do we cover this in the manual?

**Comment by rikinsk** [comment]
Content seems to be there.  Creating separate issue to track usability/discoverability of the page.

**Comment by jay-jlm** [comment]
Updated link:  https://docs.platform.hasura.io/0.15/platform/manual/project/secrets/index.html
