### ISSUE TITLE
Stop indexing obsolete sections (ref, tutorials, guides)

### ISSUE THREAD

**Issue by dsandip** [hasura/docs#241]
Not sure why but despite the ref, tutorials, and guides sections being removed, they are getting indexed in Algolia and are leading to 404s.

**Comment by karthikvt26** [comment]
I have updated the index, and pushed the changes with [commit id](https://github.com/hasura/docs/commit/718ccf6854958eb2ab32e7706d69b1cf724babea). Please check once and close if it seems to be fine.
