### ISSUE TITLE
Docs version is not indexed

### ISSUE THREAD

**Issue by wawhal** [hasura/docs#245]
![screenshot from 2017-11-20 01-21-29](https://user-images.githubusercontent.com/27274869/32994786-2ead044a-cd92-11e7-8c48-8ab42b086d60.png)

@karthikvt26 @praveenweb

**Comment by dsandip** [comment]
@karthikvt26 : So, no change needed from your end, right?

**Comment by karthikvt26** [comment]
Nope. I don't think so.

**Comment by dsandip** [comment]
A request for indexing the sitemap.xml and its links has been submitted. Will keep this open till the x.y nonsense goes away.

**Comment by dsandip** [comment]
![screen shot 2018-01-22 at 12 00 48 pm](https://user-images.githubusercontent.com/24300818/35208001-f3b15696-ff6b-11e7-9e50-107fab0925a3.png)
closing this.
