### ISSUE TITLE
Add docs and tooling for heroku to hasura migration

### ISSUE THREAD

**Issue by coco98** [hasura/docs#256]
- Architecture diagram
- Terminology guide
- How to (procfile > dockerfile)
- Advantages over heroku

Lots of heroku users in the hackathon. Let's get them all to move to hasura.

**Comment by jaisontj** [comment]
Assigning @rikinsk

**Comment by rikinsk** [comment]
https://docs.hasura.io/0.15/manual/guides/heroku-migration.html
