### ISSUE TITLE
X-Hasura-Base-Domain header not mentioned in docs

### ISSUE THREAD

**Issue by praveenweb** [hasura/docs#259]
Auth's internal endpoint required this header to be setup to work.

But there is no mention of this header in docs.

**Comment by ecthiender** [comment]
This is only required for signup, login and logout, where these endpoints are not supposed to be contacted internally. Can elaborate @praveenweb

**Comment by ecthiender** [comment]
The suggestion is to include in the docs that login, signup and logout should never be used internally.

**Comment by rikinsk** [comment]
Linking to #260
