### ISSUE TITLE
Broken Hasura CLI docs

### ISSUE THREAD

**Issue by anirudhmurali** [hasura/docs#261]
To reproduce:
https://docs.hasura.io/0.15/manual/hasuractl/hasura.html

Screenshot:
![image](https://user-images.githubusercontent.com/3096325/33702012-a8afa028-db47-11e7-917f-d8cc77d0aefb.png)

**Comment by shahidhk** [comment]
Fix: https://github.com/hasura/docs/pull/262

**Comment by praveenweb** [comment]
Merged in f86bfbb5d42306cc1bd8011fad334d8f8b9a382f
