### ISSUE TITLE
Add a hub page to list stack boilerpates on docs

### ISSUE THREAD

**Issue by coco98** [hasura/docs#272]
Make sure that it comes up on search as well.
From @anandfeb25: "Can someone add a hub page and compilation of hub projects page to docs?"

**Comment by anandfeb25** [comment]
Is this done?

**Comment by coco98** [comment]
It is indeed: https://docs.hasura.io/0.15/manual/hub/start-project.html

**Comment by coco98** [comment]
I'm just trying to make sure it comes up in search as well.

**Comment by anandfeb25** [comment]
It doesnt, people are still searching for things and not finding things.

**Comment by coco98** [comment]
@anandfeb25 It's done now.
