### ISSUE TITLE
Update advanced GKE instructions

### ISSUE THREAD

**Issue by coco98** [hasura/docs#282]
Refer conversation 👇

<img width="1195" alt="screen shot 2017-12-25 at 8 16 22 pm" src="https://user-images.githubusercontent.com/131160/34340787-89fb57b8-e9b0-11e7-8774-df274d30ab64.png">

**Comment by shahidhk** [comment]
This should be an update on manifests with `hasuractl`

**Comment by shahidhk** [comment]
Tracked here: https://github.com/hasura/hasuractl/issues/615

**Comment by shahidhk** [comment]
tracked at hasuractl
