### ISSUE TITLE
Idea to add lots of needed documentation quickly

### ISSUE THREAD

**Issue by coco98** [hasura/docs#345]
Aim: We have to make it easy for users to map features/things they want to do, to relevant hasura project files and hasura CLI commands

Recommendation:
1. Let's create a navigation section in the hasura project section: https://docs.hasura.io/0.15/manual/project/index.html that mimics the project layout. `conf/` , `migrations/`, `microservices/*/Dockerfile`, `microservices/*/k8s.yaml`,`clusters.yaml`, `hasura.yaml`. `conf/` can have further nesting.
2. For each of them let's add a page that lists out what all you can do with the files/folders on this page and what are the right hasura commands to help you
3. Let's copy the documentation from hasura/base wherever possible.

This seems like it would be easy to do and would add immediate value, searchability etc.

@rikinsk what do you think?  It'll help close a lot of pending issues on docs. Like #222 or #222 
@shahidhk Can you take this up and get it done asap? Once we have @rikinsk's blessing.

**Comment by rikinsk** [comment]
Sounds pretty good to me.

**Comment by coco98** [comment]
@shahidhk all you now :)

**Comment by shahidhk** [comment]
work at #351
