### ISSUE TITLE
Auth UI kit additional info

### ISSUE THREAD

**Issue by shark-h** [hasura/docs#355]
Please add docs on how to redirect to a custom url after login using auth ui kit (Not by passing a query parameter )

**Comment by praveenweb** [comment]
@shark-h - This is currently not possible. You should pass a query parameter for redirects to work. But we will be including this in conf - auth.yaml in the near future.

**Comment by dsandip** [comment]
@praveenweb : Can you raise a ticket is /support/issues (mark it as priority/long-term) and link it here. And then close this?

**Comment by praveenweb** [comment]
This is being tracked in hasura/platform#709 . Closing this.
