### ISSUE TITLE
CORS Settings

### ISSUE THREAD

**Issue by adevofficial** [hasura/docs#356]
For configuring the **gateway CORS Settings** it has been referred to go to Console > API Gateway > Settings > microservice There is **no such thing in the api-console** present now.

**Comment by coco98** [comment]
Thanks @adevofficial! 
Those settings have been moved to `conf/routes.yaml`
For now, check the corsPolicy key on https://docs.hasura.io/0.15/manual/project/directory-structure/conf/routes.yaml.html

@praveenweb Can you update the docs?

**Comment by dsandip** [comment]
Page to be modified: https://docs.hasura.io/0.15/manual/gateway/cors-settings.html

**Comment by praveenweb** [comment]
Fixed in bd55b1f6ca43f8c63e33300efc786c0ca4ffb54a
