### ISSUE TITLE
Auth UI Kit auto redirect to the user information

### ISSUE THREAD

**Issue by adevofficial** [hasura/docs#358]
Auth-UI-Kit when the user is login. it is automatically redirected to  **auth.<cluster-name>.hasura-app.io/v1/user/info** if there is no redirect parameter is provided. there is no way in the doc to prevent the operation. because it is exposing the API endpoint by default it is a fault. if the developer forgot to provide/user removes the query part then it exposes the API endpoint to the user.
as a developer we would like to configuer it in the config file and also need to user the query string method

**Comment by praveenweb** [comment]
Option to configure redirect_url in conf has been added. Here's the docs for configuring the same - https://docs.hasura.io/0.15/manual/users/uikit-conf.html
