### ISSUE TITLE
hasura migrations by example

### ISSUE THREAD

**Issue by coco98** [hasura/docs#360]
When talking about hasura's migration system, we should do a simple para on theory and then delve into examples immediately:

1. Creating tables via the API console
2. Adding relationships and permissions via the API console
3. Creating custom SQL views
4. Data migrations
5. Common errors: migrations not found, server is ahead, server is behind
6. Editing migration files directly
7. Resolving conflicts (db-reset and start again)

**Comment by dsandip** [comment]
@coco98 : A section on collaboration too? Like a short note on version controlling the migrations, what to do when you start collaborating on an existing project, etc.

**Comment by rikinsk** [comment]
Merge with #230
