### ISSUE TITLE
doc spell correction

### ISSUE THREAD

**Issue by adevofficial** [hasura/docs#361]
/# this command will fetch credentials, adds your ssh key to each cluster and sets up hooks and remotes
/# note: this command is only available in this **form from** v0.2.37 onwards
$ hasura setup

on page : https://docs.hasura.io/0.15/manual/project/collaboration.html

**Comment by dsandip** [comment]
@adevofficial : Thank you for pointing this out. Would love to see a simple PR from you. You will need to modify this page: https://github.com/hasura/docs/blob/master/manual/project/collaboration.rst. What say?

**Comment by rikinsk** [comment]
This seems to be intentional.
