### ISSUE TITLE
Auth UI kit is not usable according to docs

### ISSUE THREAD

**Issue by coco98** [hasura/docs#383]
Auth UI kit is very useful to everyone. However, no one can use it right now because the docs don't help. 

The docs should have the following sections:

1. Use-cases: when to use auth-ui Kit
2. Use case based sample configurations
3. How will other API calls automatically have the right token info? Localstorage or cookies? How will this work with API codegen which generates localStorage type code?

In its current state, the auth UI kit is not useful to anyone.

--
Tanmai

**Comment by praveenweb** [comment]
Updated docs with usage, sample conf - https://docs.hasura.io/0.15/manual/users/uikit.html
