### ISSUE TITLE
UI changes for Ref and Guides/Tutorials sections

### ISSUE THREAD

**Issue by dsandip** [hasura/docs#41]
1. The gutter space for the header and the Ref section (sidebar + content space) are not equal - 5% and 15%. Change the latter to 5% also.

![screen shot 2017-07-18 at 11 42 50 am](https://user-images.githubusercontent.com/24300818/28302998-4b8f9e7e-6bae-11e7-9ee6-ee1bcf244432.png)

2. The same is true in the Tutorials/Guides landing pages:

![screen shot 2017-07-18 at 11 44 42 am](https://user-images.githubusercontent.com/24300818/28303040-9256c4c2-6bae-11e7-8c15-6b11483ab434.png)

3. Change the background color of the Ref content space to the same background as in the Tutorials/Guides landing page.

**Comment by surendran82** [comment]
Fixed the issue
