### ISSUE TITLE
Font changes in the modified sidebar

### ISSUE THREAD

**Issue by dsandip** [hasura/docs#42]
The fonts in the modified sidebar are not as per the design. Please change it to Gudea and 16px.

**Comment by dsandip** [comment]
@surendran82 : Looks like the font is different for the following elements also:
1. TOCs or Table of Contents
2. Ordered or Unordered lists
@karthikvt26 : Can you please point @surendran82 to where these can be modified?

**Comment by surendran82** [comment]
Fixed the issue
