### ISSUE TITLE
[guides] Integrating social login with user table 

### ISSUE THREAD

**Issue by jaisontj** [hasura/docs#435]

**Comment by coco98** [comment]
Proposed outline:

- What this guide will help you do
- What you should have already done (configure social provider and auth)
- For access to more info that what hasura needs for login, set up the scopes variable
- How to get the access token, refresh token (different for different providers) on the client-side
- How to store the access token in a data table
- Where can you use this access token

Caveats (for us):
- Some providers give you different access tokens for the server and mobile in which case the auth provider stuff cannot be easily linked
