### ISSUE TITLE
Remove orphaned files from the manual/ directory

### ISSUE THREAD

**Issue by coco98** [hasura/docs#443]
They're turning up on google search and they're outdated docs.

Google for 'hasura ssh'
One user found this issue: https://docs.hasura.io/0.15/manual/SSH-cluster.html
and got super pained because the dashboard does not have that anymore.

**Comment by rikinsk** [comment]
Fixed this issue already. Orphaned docs used to be present in our sitemap.xml. This doesn't happen anymore.

**Comment by rikinsk** [comment]
We need to somehow make google forget already crawled links. Webmaster lets me remove pages one url at a time which is super painful.
