### ISSUE TITLE
Data API reference error in order_by syntax

### ISSUE THREAD

**Issue by shahidhk** [hasura/docs#50]
https://docs.hasura.io/0.13/ref/hasura-microservices/data/query/data/select.html#orderbyitem

given:
```json
{
    "column" : PGColumn,
    "order"  : "asc" | "desc",
    "nulls"  : "first" | "last"
}
```

should be 
```json
{
    "column" : PGColumn,
    "type"  : "asc" | "desc",
    "nulls"  : "first" | "last"
}
```

**Comment by praveenweb** [comment]
Both keys work. The latest docs seem to be having "order" everywhere. So lets not change it?

@0x777 ?
