### ISSUE TITLE
Lot of redirects on docs.hasura.io

### ISSUE THREAD

**Issue by karthikvt26** [hasura/docs#61]
> wget docs.hasura.io

>--2017-07-21 16:20:51--  http://docs.hasura.io/
Resolving docs.hasura.io... 35.187.252.229
Connecting to docs.hasura.io|35.187.252.229|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://docs.hasura.io/ [following]
--2017-07-21 16:20:52--  https://docs.hasura.io/
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Connecting to docs.hasura.io|35.187.252.229|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: http://docs.hasura.io/0.13 [following]
--2017-07-21 16:20:52--  http://docs.hasura.io/0.13
Connecting to docs.hasura.io|35.187.252.229|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://docs.hasura.io/0.13 [following]
--2017-07-21 16:20:53--  https://docs.hasura.io/0.13
Connecting to docs.hasura.io|35.187.252.229|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://docs.hasura.io/0.13/ [following]
--2017-07-21 16:20:53--  http://docs.hasura.io/0.13/
Connecting to docs.hasura.io|35.187.252.229|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://docs.hasura.io/0.13/ [following]
--2017-07-21 16:20:53--  https://docs.hasura.io/0.13/
Connecting to docs.hasura.io|35.187.252.229|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 19748 (19K) [text/html]
Saving to: 'index.html'

**Comment by rikinsk** [comment]
Only 2 redirects as of now. http to https, then / to /0.15/manual/getting-started/index.html. Both legit.
