### ISSUE TITLE
The size of the guides/tutorial cards needs to be standardized

### ISSUE THREAD

**Issue by dsandip** [hasura/docs#64]
1. The title part should always have space for 2 lines (or 90 characters). That way the images, title and the rest of the content will be aligned.
![screen shot 2017-07-24 at 11 57 34 am](https://user-images.githubusercontent.com/24300818/28510765-beadb0e0-7067-11e7-8bf0-f4a6287f761f.png)

1. Reduce the space after the description. We can take a look at the spacing for tags etc. when we revisit adding tags. Right now the cards look unnecessarily big.

**Comment by surendran82** [comment]
Issue is fixed

**Comment by dsandip** [comment]
@karthikvt26 : This isn't live yet. Can you please check up on it?

**Comment by rikinsk** [comment]
Not relevant anymore.
