### ISSUE TITLE
Suggestions for the Getting Started section

### ISSUE THREAD

**Issue by paranoidsp** [hasura/docs#66]
These are suggestions for the [Getting Started](https://docs.hasura.io/0.13/getting-started/) section.
* Each part of the tutorial should have a next part link(at the top/bottom or both) that takes the user to the next section.  Currently there is no such link, and the user has to go back to the getting started page to progress.
* In Part 2 -  A mention could be made of the user table in the data section of the console.  This is shown in the videos, but not mentioned in the text. The text does not refer to the console anywhere. Or is this intentional?  The videos demo the console, and the text explains the api? If that is the case, let us make that clear by explicitly stating so.
* Also useful would be a mention at the bottom of the page of how users can expect to make use of the session headers set by the hasura platform in their code, similar to the example we currently have in our features page, a small snippet of code. This is intended to make clear to users the practical upshot of all the session middleware, and how they can expect to make use of it in their backend code. 
* Documentation for 'run_sql' is missing under the Data section of the API Reference.  This is the case even for the older 0.6 version documentation. 
* In Part 4 - Under Importing seed data, we could make it clear that the psql command is supposed to be run on your local machine, not in the ssh session just started.  This is mostly to clear up beginner confusion.
* In Part 5 - The first json request is made with type 'raw_sql' - this should be 'run_sql'.
* Part 7 mentions the git-push-templates repo, which we've deprecated in favor of [quickstart-docker-git](https://github.com/hasura/quickstart-docker-git). This also needs to be changed in the other places it is mentioned.  I'll try to submit a pull request for this and some of the other changes I listed here when I can.
* In Part 7, under git push deployment, we can make it clearer that people are to copy the quickstart template from the cloned repo into another folder and then use that for their project. 
* Part 7 also does not mention that the hasura project has to be added as a remote before pushing.
Also we should have a line at the end that concludes the tutorial, and directs them to the API reference and the tutorials home for further reading.

**Comment by paranoidsp** [comment]
I've added some of the above fixes as a pull request( #67 ), please review and comment.

**Comment by dsandip** [comment]
Not doing this any more
