### ISSUE TITLE
Custom Microservices section is incomplete

### ISSUE THREAD

**Issue by paranoidsp** [hasura/docs#68]
These are issues with the  [Custom Microservices section](https://docs.hasura.io/0.13/ref/custom-microservices/index.html) in the docs -
* The creating a git push portion does not actually explain how to add the hasura remote or actually use git push to deploy the service.
* The Managing a custom microservice portion is completely empty.

**Comment by paranoidsp** [comment]
Added a commit to pull request #67 with the following changes
* Added a deploy subsection to the Create a git push service page.

The following problems still exist
* Managing a custom microservice section is still empty.
* Images need to be updated with the newer console ui.

**Comment by dsandip** [comment]
handled by hasura CLI.
