### ISSUE TITLE
CSS change for Text highlight and link hover

### ISSUE THREAD

**Issue by dsandip** [hasura/docs#7]
References to the Djangodocs theme are still being used when highlighting text and hovering over a link: 

![screen shot 2017-07-12 at 12 47 56 pm](https://user-images.githubusercontent.com/24300818/28106217-988e26f8-6700-11e7-8998-2c8abb9bd608.png)

**Comment by coco98** [comment]
I don't mind the green highlight to be honest. :)
Should we switch it back to the browser default, or yellow? Not sure about yellow at all.

**Comment by dsandip** [comment]
Not very high priority according to me. I am creating a laundry list and will mark the priority on each one.

**Comment by surendran82** [comment]
Fixed the issue
