### ISSUE TITLE
Logs section just says WIP

### ISSUE THREAD

**Issue by paranoidsp** [hasura/docs#70]
There is no information about logs in the documentation, no mention of where to find them, or how the logs are collected. This is one of the smaller but important parts of the documentation.

**Comment by paranoidsp** [comment]
Updated with a single line and an image, will add content from https://docs.hasura.io/0.6/cookbooks/logging-monitoring.html next.

**Comment by dsandip** [comment]
Handled in the new(since this issue was created) version of docs
