### ISSUE TITLE
Redirects for old URLs 

### ISSUE THREAD

**Issue by dsandip** [hasura/docs#89]
A complete list of old URLs that are now throwing 404s: https://docs.google.com/a/hasura.io/spreadsheets/d/1AqTbUcnJ5h8iBnWa8Q3v23_4zrtQaWy_NyTZQpyRCLg/edit?usp=sharing.

**Comment by dsandip** [comment]
List of redirects needed:

http://hasura.io/blog/ -> https://blog.hasura.io
http://hasura.io/blog/* -> https://blog.hasura.io
https://hasura.io/_docs/ -> https://docs.hasura.io
https://hasura.io/_docs/* -> https://docs.hasura.io
https://hasura.io/services/ -> https://hasura.io/#features
https://hasura.io/services/* -> https://hasura.io/#features
https://hasura.io/s/ -> https://hasura.io
https://hasura.io/s/* -> https://hasura.io
https://hasura.io/policy/ -> https://hasura.io/privacy-policy
https://hasura.io/policy/* -> https://hasura.io/privacy-policy

**Comment by dsandip** [comment]
@0x777 : Please review. Too many 404s happening.

**Comment by rikinsk** [comment]
Closing this.
