### ISSUE TITLE
Add category name to the hasura/docs

### ISSUE THREAD

**Issue by coco98** [hasura/docs#94]
Instead of just showing the search results can you also show the category name?

**Building an Android app using a Java based backend**
A tutorial on building an Android app using Hasura

Changes to:
**Tutorials / Building an Android app using a Java based backend**
A tutorial on building an Android app using Hasura

**Comment by coco98** [comment]
https://docs.hasura.io/0.14/tutorials/deploying-a-php-laravel-app.html
Has:
1. Hasura deployment
2. Local development
3. Migrations

**Comment by dsandip** [comment]
Not relevant anymore as the structure of docs has changed
