### ISSUE TITLE
MySQL quickstart as a tutorial or guide

### ISSUE THREAD

**Issue by paranoidsp** [hasura/docs#96]
Have a version of https://blog.hasura.io/the-easiest-way-to-deploy-wordpress-using-docker-kubernetes-on-hasura-4bbae1d60e98 on the docs as a tutorial or a guide for people who search for mysql.

**Comment by dsandip** [comment]
This should be handled via quickstarts or microservice templates. And the content from qs and templates can perhaps be indexed in docs to support search.
